### ISSUE TITLE
Clarification ... Does babylon allow parsing 'import' and 'export'

### ISSUE THREAD

**Issue by annamalai-saro** [thejameskyle/babel-plugin-handbook#4]
```js
import {parse} from "babylon";
import traverse from "babel-traverse";
import {readFileSync} from 'fs';

const code = `import Ember from 'ember';    //No I18N
export default Ember.View.extend({
   classNames    :   ["full-height","flex"]//No I18N
});
`;
const ast = parse(code);
console.log(ast);
```

I get error

```
/Volumes/Official/classo/node_modules/babylon/lib/parser/location.js:27
  throw err;
  ^

SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
    at Parser.pp.raise (/Volumes/Official/classo/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.parseStatement (/Volumes/Official/classo/node_modules/babylon/lib/parser/statement.js:134:16)
    at Parser.pp.parseBlockBody (/Volumes/Official/classo/node_modules/babylon/lib/parser/statement.js:529:25)
    at Parser.pp.parseTopLevel (/Volumes/Official/classo/node_modules/babylon/lib/parser/statement.js:31:8)
    at Parser.parse (/Volumes/Official/classo/node_modules/babylon/lib/parser/index.js:98:17)
    at parse (/Volumes/Official/classo/node_modules/babylon/lib/index.js:46:50)
    at Object.<anonymous> (parser.js:1:14)
    at Module._compile (module.js:425:26)
    at loader (/Volumes/Official/classo/node_modules/babel-register/lib/node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Volumes/Official/classo/node_modules/babel-register/lib/node.js:138:7)
```

**Comment by fkling** [comment]
You have to set `sourceType: 'module'` in the options:

    parse(code, {sourceType: 'module'})

**Comment by thejameskyle** [comment]
Yeah, the [default `sourceType` is `"script"`](https://github.com/babel/babel/blob/d2e07cffb99b0d000eabf966687ec8526c3f08b3/packages/babylon/src/options.js#L5-L6).

I'll see if I can clarify that at all

**Comment by annamalai-saro** [comment]
:+1:  works !! @fkling  @thejameskyle
